-- LLMobi catalog seed.
-- Generated from Catalog.kt by tools/gen_seed.py - do not hand-edit.

INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('qwen25-05b','Qwen 0.5B','Tiny and instant. Good for quick questions.','tiny','general','Q','#7BD4F5','#3C8FD0','0.40 GB','very fast',428730208,1012,2048,'qwen2','Q4_0','Qwen/Qwen2.5-0.5B-Instruct-GGUF','qwen2.5-0.5b-instruct-q4_0.gguf','https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_0.gguf','apache-2.0','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('llama32-1b','Llama 1B','Meta''s small everyday assistant.','tiny','general','L','#F5C77B','#D08A34','0.95 GB','very fast',1021800576,1719,4096,'llama','Q6_K','bartowski/Llama-3.2-1B-Instruct-GGUF','Llama-3.2-1B-Instruct-Q6_K.gguf','https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q6_K.gguf','llama-3.2-community','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('gemma3-1b','Gemma 1B','Google''s compact model. Neat writer.','tiny','general','G','#9BE7C4','#3FA47C','0.94 GB','very fast',1011738880,1707,4096,'gemma3','Q6_K','bartowski/google_gemma-3-1b-it-GGUF','google_gemma-3-1b-it-Q6_K.gguf','https://huggingface.co/bartowski/google_gemma-3-1b-it-GGUF/resolve/main/google_gemma-3-1b-it-Q6_K.gguf','gemma-terms','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('qwen3-17b','Qwen 1.7B','Small but sharp. Handles many languages.','tiny','multilingual','Q','#7BD4F5','#3C8FD0','1.4 GB','fast',1471805856,2255,4096,'qwen3','Q5_K_M','bartowski/Qwen_Qwen3-1.7B-GGUF','Qwen_Qwen3-1.7B-Q5_K_M.gguf','https://huggingface.co/bartowski/Qwen_Qwen3-1.7B-GGUF/resolve/main/Qwen_Qwen3-1.7B-Q5_K_M.gguf','apache-2.0','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('llama32-3b','Llama 3B','Solid all-rounder for everyday questions.','fast','general','L','#F5C77B','#D08A34','1.9 GB','fast',2019377696,2908,4096,'llama','Q4_K_M','bartowski/Llama-3.2-3B-Instruct-GGUF','Llama-3.2-3B-Instruct-Q4_K_M.gguf','https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf','llama-3.2-community','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('phi4-mini','Phi 3.8B','Microsoft''s small model. Strong at maths.','fast','reasoning','P','#F6A5A5','#CE5757','2.3 GB','fast',2491874688,3471,4096,'phi3','Q4_K_M','bartowski/microsoft_Phi-4-mini-instruct-GGUF','microsoft_Phi-4-mini-instruct-Q4_K_M.gguf','https://huggingface.co/bartowski/microsoft_Phi-4-mini-instruct-GGUF/resolve/main/microsoft_Phi-4-mini-instruct-Q4_K_M.gguf','mit','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('qwen3-4b','Qwen 4B','Thinks things through. Many languages.','fast','reasoning','Q','#7BD4F5','#3C8FD0','2.3 GB','fast',2497280960,3477,4096,'qwen3','Q4_K_M','bartowski/Qwen_Qwen3-4B-GGUF','Qwen_Qwen3-4B-Q4_K_M.gguf','https://huggingface.co/bartowski/Qwen_Qwen3-4B-GGUF/resolve/main/Qwen_Qwen3-4B-Q4_K_M.gguf','apache-2.0','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('gemma3-4b','Gemma 4B','Everyday AI. Can also look at pictures.','fast','vision','G','#9BE7C4','#3FA47C','2.3 GB','fast',2489758112,3469,4096,'gemma3','Q4_K_M','bartowski/google_gemma-3-4b-it-GGUF','google_gemma-3-4b-it-Q4_K_M.gguf','https://huggingface.co/bartowski/google_gemma-3-4b-it-GGUF/resolve/main/google_gemma-3-4b-it-Q4_K_M.gguf','gemma-terms','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('mistral-7b','Mistral 7B','Fast European model. Clean writing.','powerful','general','M','#FFB088','#D1591F','4.1 GB','steady',4372812000,5713,4096,'llama','Q4_K_M','bartowski/Mistral-7B-Instruct-v0.3-GGUF','Mistral-7B-Instruct-v0.3-Q4_K_M.gguf','https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf','apache-2.0','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('deepseek-r1-7b','DeepSeek 7B','Shows its thinking before answering.','powerful','reasoning','D','#C3B0F7','#6E58C9','4.4 GB','steady',4683073504,6083,4096,'qwen2','Q4_K_M','bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF','DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf','https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf','mit','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('qwen25-coder-7b','Qwen Coder 7B','Writes and fixes code.','powerful','coding','C','#8FE3C4','#2C8F6B','4.4 GB','steady',4683074336,6083,8192,'qwen2','Q4_K_M','bartowski/Qwen2.5-Coder-7B-Instruct-GGUF','Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf','https://huggingface.co/bartowski/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf','apache-2.0','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('llama31-8b','Llama 8B','Strong general assistant.','powerful','general','L','#F5C77B','#D08A34','4.6 GB','steady',4920739232,6366,4096,'llama','Q4_K_M','bartowski/Meta-Llama-3.1-8B-Instruct-GGUF','Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf','https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf','llama-3.1-community','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('qwen3-8b','Qwen 8B','Reasoning and 100+ languages.','powerful','multilingual','Q','#7BD4F5','#3C8FD0','4.7 GB','steady',5027784224,6494,4096,'qwen3','Q4_K_M','bartowski/Qwen_Qwen3-8B-GGUF','Qwen_Qwen3-8B-Q4_K_M.gguf','https://huggingface.co/bartowski/Qwen_Qwen3-8B-GGUF/resolve/main/Qwen_Qwen3-8B-Q4_K_M.gguf','apache-2.0','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('gemma3-12b','Gemma 12B','Noticeably smarter. Needs a big phone.','pro','general','G','#9BE7C4','#3FA47C','6.8 GB','slow',7300575264,9203,4096,'gemma3','Q4_K_M','bartowski/google_gemma-3-12b-it-GGUF','google_gemma-3-12b-it-Q4_K_M.gguf','https://huggingface.co/bartowski/google_gemma-3-12b-it-GGUF/resolve/main/google_gemma-3-12b-it-Q4_K_M.gguf','gemma-terms','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('qwen3-14b','Qwen 14B','Serious reasoning power.','pro','reasoning','Q','#7BD4F5','#3C8FD0','8.4 GB','slow',9001753632,11231,4096,'qwen3','Q4_K_M','bartowski/Qwen_Qwen3-14B-GGUF','Qwen_Qwen3-14B-Q4_K_M.gguf','https://huggingface.co/bartowski/Qwen_Qwen3-14B-GGUF/resolve/main/Qwen_Qwen3-14B-Q4_K_M.gguf','apache-2.0','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('deepseek-r1-14b','DeepSeek 14B','Works through hard problems step by step.','pro','reasoning','D','#C3B0F7','#6E58C9','8.4 GB','slow',8988110240,11215,4096,'qwen2','Q4_K_M','bartowski/DeepSeek-R1-Distill-Qwen-14B-GGUF','DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf','https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-14B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf','mit','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('phi4-14b','Phi 14B','Excellent at maths and logic.','pro','reasoning','P','#F6A5A5','#CE5757','8.4 GB','slow',9053114816,11293,4096,'phi3','Q4_K_M','bartowski/phi-4-GGUF','phi-4-Q4_K_M.gguf','https://huggingface.co/bartowski/phi-4-GGUF/resolve/main/phi-4-Q4_K_M.gguf','mit','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('gpt-oss-20b','GPT-OSS 20B','Very capable. Only for huge-memory phones.','extreme','general','O','#B8B8B8','#5A5A5A','11.3 GB','very slow',12109566624,14936,4096,'gptoss','Q4','ggml-org/gpt-oss-20b-GGUF','gpt-oss-20b-MXFP4.gguf','https://huggingface.co/ggml-org/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-MXFP4.gguf','apache-2.0','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('gemma3-27b','Gemma 27B','Near desktop quality. Experimental on phones.','extreme','general','G','#9BE7C4','#3FA47C','15.4 GB','very slow',16546404992,20225,4096,'gemma3','Q4_K_M','bartowski/google_gemma-3-27b-it-GGUF','google_gemma-3-27b-it-Q4_K_M.gguf','https://huggingface.co/bartowski/google_gemma-3-27b-it-GGUF/resolve/main/google_gemma-3-27b-it-Q4_K_M.gguf','gemma-terms','live',0);
INSERT OR REPLACE INTO models (id,name,tagline,tier,category,icon_letter,color_start,color_end,size_label,speed_hint,file_bytes,min_ram_mb,ctx_default,arch,quant,hf_repo,hf_file,url,license,status,updated_at) VALUES ('qwen3-32b','Qwen 32B','The largest we list. Almost no phone runs it.','extreme','reasoning','Q','#7BD4F5','#3C8FD0','18.4 GB','very slow',19762149696,24059,4096,'qwen3','Q4_K_M','bartowski/Qwen_Qwen3-32B-GGUF','Qwen_Qwen3-32B-Q4_K_M.gguf','https://huggingface.co/bartowski/Qwen_Qwen3-32B-GGUF/resolve/main/Qwen_Qwen3-32B-Q4_K_M.gguf','apache-2.0','live',0);
